<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatsIntentsSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('pats_bot_intents')->count() > 0) {
            return;
        }

        DB::table('pats_bot_intents')->insert([
            ['id' => 1,  'intent' => 'que_es_pats',          'nombre' => 'Qué es PATS',                'descripcion' => 'Explica qué es Pasaporte a tu Salud con lenguaje simple para usuario final y personal interno.',        'keywords' => 'pats,pasaporte,pasaporte a tu salud,que es,que significa,para que sirve,programa,beneficios,descuentos,precio preferencial,tarjeta', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 2,  'intent' => 'no_seguro',             'nombre' => 'PATS no es seguro médico',   'descripcion' => 'Aclara que PATS no es póliza, seguro ni cobertura aseguradora.',                                        'keywords' => 'seguro,seguro medico,poliza,cobertura,aseguradora,gastos medicos,no es seguro,me cubre,cubre,le cubre', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 3,  'intent' => 'beneficios',            'nombre' => 'Beneficios PATS',             'descripcion' => 'Explica beneficios generales, precios preferenciales y servicios aplicables.',                           'keywords' => 'beneficios,incluye,que incluye,servicios,descuentos,precio preferencial,preferente,beneficio,gratis,sin costo,aplica', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 4,  'intent' => 'costo',                 'nombre' => 'Costo PATS',                  'descripcion' => 'Explica costo mensual, anual y diferencia entre pago de pasaporte y pago de servicios.',                'keywords' => 'costo,precio,cuanto cuesta,cuanto vale,mensualidad,anualidad,pago mensual,pago anual,800,9600,cuota', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 5,  'intent' => 'pago',                  'nombre' => 'Pagos PATS',                  'descripcion' => 'Explica medios, referencias y lugares de pago autorizados.',                                            'keywords' => 'pago,pagar,donde pago,donde se paga,como pago,medios de pago,formas de pago,opciones de pago,caja,oxxo,transferencia,spei,link,referencia,ficha,comprobante,ticket,recibo', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 6,  'intent' => 'vigencia',              'nombre' => 'Vigencia PATS',               'descripcion' => 'Explica cómo validar si PATS está activo, vigente o próximo a vencer.',                               'keywords' => 'vigencia,vigente,activo,activa,estatus,estado,fecha de corte,vencimiento,vence,cuando vence,validar vigencia,consultar estatus', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 7,  'intent' => 'falta_pago',            'nombre' => 'Falta de pago',               'descripcion' => 'Explica consecuencias de no pagar o tener PATS vencido/inactivo.',                                      'keywords' => 'no pague,deje de pagar,no pago,vencido,vencio,venido,inactivo,suspendido,adeudo,atrasado,bloqueado,no vigente', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 8,  'intent' => 'reactivacion',          'nombre' => 'Reactivación PATS',           'descripcion' => 'Explica ruta general para reactivar PATS con pago o validación autorizada.',                            'keywords' => 'reactivar,reactivacion,activar,volver a activar,volver a usar,activar pasaporte,comprobante,voucher,restablecer,vencido', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 9,  'intent' => 'acceso_app',            'nombre' => 'Acceso a la app',             'descripcion' => 'Explica entrega de usuario, contraseña y acceso digital.',                                              'keywords' => 'usuario,contraseña,password,correo,app,acceso,login,qr', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 10, 'intent' => 'uso_qr',                'nombre' => 'Uso QR / Pasaporte digital',  'descripcion' => 'Explica uso de QR, identificación digital y validación de identidad.',                               'keywords' => 'qr,codigo qr,pasaporte digital,tarjeta digital,identificacion,ine,no aparece qr,no tengo qr,no sale qr,app,codigo', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 11, 'intent' => 'consulta_general',      'nombre' => 'Consulta general',            'descripcion' => 'Explica uso de PATS para consulta de medicina general.',                                               'keywords' => 'consulta general,medicina general,doctor general,medico general,consulta,consulta medica', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 12, 'intent' => 'urgencias',             'nombre' => 'Urgencias',                   'descripcion' => 'Explica uso de PATS en urgencias sin prometer cobertura ni disponibilidad.',                           'keywords' => 'urgencias,emergencia,consulta urgencias,procedimiento urgencias,accidente,me siento mal,atencion urgente', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 13, 'intent' => 'especialistas',         'nombre' => 'Especialistas',               'descripcion' => 'Explica uso de PATS con especialistas y necesidad de agenda/red autorizada.',                          'keywords' => 'especialista,especialidad,medico especialista,consulta especialidad,cita,agenda,cardiologo,ginecologo,pediatra,traumatologo', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 14, 'intent' => 'laboratorio',           'nombre' => 'Laboratorio',                 'descripcion' => 'Explica uso de PATS para estudios de laboratorio y validación de indicaciones/precio.',                'keywords' => 'laboratorio,lab,analisis,biometria,quimica sanguinea,estudio clinico,muestra,sangre,orina', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 15, 'intent' => 'imagenologia',          'nombre' => 'Imagenología',                'descripcion' => 'Explica uso de PATS en rayos X, ultrasonido, tomografía y otros estudios.',                           'keywords' => 'imagen,imagenologia,rayos,rayos x,ultrasonido,eco,tomografia,resonancia,placa,mastografia', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 16, 'intent' => 'farmacia',              'nombre' => 'Farmacia',                    'descripcion' => 'Explica uso de PATS en farmacia, receta y medicamentos según red autorizada.',                        'keywords' => 'farmacia,medicamento,medicamentos,medicinas,receta,surtir,comprar medicamento', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 17, 'intent' => 'hospitalizacion',       'nombre' => 'Hospitalización',             'descripcion' => 'Explica que hospitalización requiere validación/cotización y reglas específicas.',                     'keywords' => 'hospitalizacion,hospital,internamiento,cuarto,dia hospital,servicios hospitalarios,enfermeria', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 18, 'intent' => 'cirugia',               'nombre' => 'Cirugía / procedimiento',     'descripcion' => 'Explica que cirugías o procedimientos requieren cotización y autorización de red.',                    'keywords' => 'cirugia,operacion,procedimiento quirurgico,quirofano,honorarios,anestesia,paquete quirurgico', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 19, 'intent' => 'terapia_intensiva',     'nombre' => 'Terapia intensiva',           'descripcion' => 'Reglas para terapia intensiva.',                                                                       'keywords' => 'terapia intensiva,uci,uti,intensiva', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 20, 'intent' => 'precios_servicios',     'nombre' => 'Precios de servicios',        'descripcion' => 'Explica que precios de estudios/servicios se validan en fuente autorizada.',                          'keywords' => 'precio servicio,precio estudio,precio consulta,precio especialista,tabulador,pats money,money,costo estudio,costo consulta', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 21, 'intent' => 'uso_ilimitado',         'nombre' => 'Uso frecuente / límites',     'descripcion' => 'Explica uso recurrente, validaciones y que cada servicio se revisa según reglas.',                     'keywords' => 'uso ilimitado,cuantas veces,limite,limites,preexistencias,puedo usar muchas veces,veces', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 22, 'intent' => 'exclusiones',           'nombre' => 'Exclusiones',                 'descripcion' => 'Explica límites y exclusiones generales sin lenguaje de seguro.',                                     'keywords' => 'no incluye,exclusion,exclusiones,no cubre,trasplante,oncologico,hemodialisis,experimental,alto costo', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 23, 'intent' => 'fuera_red',             'nombre' => 'Fuera de red',                'descripcion' => 'Aclara que fuera de red autorizada no se deben prometer beneficios.',                                  'keywords' => 'fuera de red,no afiliado,no autorizado,otro hospital,otro medico,no convenio,no pertenece a la red', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 24, 'intent' => 'mayores_65',            'nombre' => 'Mayores de 65 años',          'descripcion' => 'Explica reglas o validación especial para adultos mayores.',                                           'keywords' => '65,mayor de 65,adulto mayor,sesenta y cinco,tercera edad', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 25, 'intent' => 'menores_dependientes',  'nombre' => 'Menores y dependientes',      'descripcion' => 'Explica uso para menores/dependientes con tutor y validación de identidad.',                          'keywords' => 'menor,menores,18 anos,dependiente,tutor,padre,madre,hijo,hija', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 26, 'intent' => 'cancelacion',           'nombre' => 'Cancelación / baja',          'descripcion' => 'Explica baja, cancelación, no renovación y revisión administrativa.',                                 'keywords' => 'cancelar,cancelacion,baja,terminar,no renovar,reembolso,devolucion,ya no quiero', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 27, 'intent' => 'responsabilidad_medica','nombre' => 'Responsabilidad médica',      'descripcion' => 'Aclara responsabilidad de prestadores médicos.',                                                       'keywords' => 'responsabilidad medica,negligencia,resultado medico,doctor,hospital,prestador', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 28, 'intent' => 'privacidad',            'nombre' => 'Privacidad y datos',          'descripcion' => 'Explica uso de datos personales y privacidad.',                                                       'keywords' => 'datos personales,privacidad,arco,cifrado,proteccion de datos,lfpdppp,mis datos', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 29, 'intent' => 'recomendaciones',       'nombre' => 'Recomendaciones de uso',      'descripcion' => 'Consejos para usar PATS correctamente.',                                                              'keywords' => 'recomendaciones,consejos,usar bien,pagar a tiempo,verificar red,evitar problemas', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 30, 'intent' => 'canalizar',             'nombre' => 'Canalizar con personal',      'descripcion' => 'Indica cuándo enviar al usuario con Concierge, Admisión, Caja o ADMINPATS.',                          'keywords' => 'concierge,admision,caja,soporte,ayuda,asesor,personal autorizado,a quien mando,quien ayuda', 'activo' => 1, 'created_at' => '2026-04-24 07:46:25'],
            ['id' => 31, 'intent' => 'cotizacion',            'nombre' => 'Cotización',                  'descripcion' => 'Explica cuándo se requiere cotización, alcance y canal correcto.',                                    'keywords' => 'cotiza,cotizar,cotizacion,presupuesto,lead,precio cirugia,procedimiento,paquete,quien cotiza', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
            ['id' => 32, 'intent' => 'red_autorizada',        'nombre' => 'Red autorizada',              'descripcion' => 'Explica que PATS aplica en red, unidad y prestadores autorizados.',                                   'keywords' => 'red,red autorizada,hospital autorizado,unidad autorizada,prestador,medico autorizado,convenio,afiliado', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
            ['id' => 33, 'intent' => 'queja_cobro',           'nombre' => 'Queja o cobro incorrecto',    'descripcion' => 'Ruta para reclamos, inconformidades, cobros o beneficio no respetado.',                               'keywords' => 'queja,reclamo,inconformidad,cobro,cobraron mal,no respetaron,me cobraron,no aplicaron descuento', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
            ['id' => 34, 'intent' => 'login_acceso',          'nombre' => 'Acceso a cuenta / app',       'descripcion' => 'Dudas de acceso, contraseña, usuario o pasaporte digital.',                                           'keywords' => 'login,acceso,entrar,no puedo entrar,contrasena,password,usuario,crear password,restablecer', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
            ['id' => 35, 'intent' => 'documentos',            'nombre' => 'Documentos requeridos',       'descripcion' => 'Identificación, comprobantes y datos que pueden solicitarse.',                                        'keywords' => 'documentos,ine,identificacion,comprobante,curp,rfc,foto,archivo,pdf', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
            ['id' => 36, 'intent' => 'facturacion',           'nombre' => 'Facturación',                 'descripcion' => 'Dudas de factura, datos fiscales y comprobantes.',                                                    'keywords' => 'factura,facturacion,cfdi,rfc,constancia fiscal,datos fiscales,xml,pdf', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
            ['id' => 37, 'intent' => 'renovacion',            'nombre' => 'Renovación',                  'descripcion' => 'Renovar PATS mensual o anual.',                                                                       'keywords' => 'renovar,renovacion,renueva,renovado,proximo mes,siguiente pago,renovar anual', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
            ['id' => 38, 'intent' => 'descuento_no_aplicado', 'nombre' => 'Descuento no aplicado',       'descripcion' => 'Cuando el usuario dice que no le aplicaron precio preferencial.',                                     'keywords' => 'no aplicaron descuento,no respetaron descuento,no me hicieron descuento,precio normal,cobro sin beneficio', 'activo' => 1, 'created_at' => '2026-05-28 22:31:58'],
        ]);
    }
}
