    @php
        use Illuminate\Support\Str;

        $hospitales = [
            [
                'nombre' => 'Fifty Doctors Angelópolis',
                'direccion' => 'Anillo Perif. Ecológico 3505, Tlaxcalancingo, San Andrés Cholula, Pue.',
                'telefono' => '2226892995',
                'horario' => 'Abierto las 24 hrs',
                'imagen' => 'images/hospitals/angelopolis.jpeg',
            ],
            [
                'nombre' => 'Fifty Doctors San Manuel',
                'direccion' => 'Blvrd 14 Sur 4302, Jardines de San Manuel, Puebla',
                'telefono' => '2226895140',
                'horario' => 'Abierto las 24 hrs',
                'imagen' => 'images/hospitals/angelopolis.jpeg',
            ],
            [
                'nombre' => 'Fifty Doctors Homi La Paz',
                'direccion' => 'Av. Teziutlán Sur 36, Col. La Paz, Puebla',
                'telefono' => '2226895140',
                'horario' => 'Abierto las 24 hrs',
                'imagen' => 'images/hospitals/angelopolis.jpeg',
            ],
        ];

        $doctores = [
            [
                'nombre' => 'Adrián Castillo Moreno',
                'especialidad' => 'Medicina Interna',
                'telefono' => '5532894412',
                'telefono_format' => '55 3289 4412',
                'direccion' => 'Av. Universidad 850, Col. Narvarte, CDMX',
            ],
            [
                'nombre' => 'Alejandro Martínez López',
                'especialidad' => 'Traumatología y Ortopedia',
                'telefono' => '5541238890',
                'telefono_format' => '55 4123 8890',
                'direccion' => 'Av. Insurgentes Sur 1450, Col. Del Valle, CDMX',
            ],
            [
                'nombre' => 'Andrea Robles Fuentes',
                'especialidad' => 'Dermatología',
                'telefono' => '5590037721',
                'telefono_format' => '55 9003 7721',
                'direccion' => 'Río Rhin 40, Col. Cuauhtémoc, CDMX',
            ],
            [
                'nombre' => 'Arturo Peña Salgado',
                'especialidad' => 'Cirugía General',
                'telefono' => '3320115598',
                'telefono_format' => '33 2011 5598',
                'direccion' => 'Av. Vallarta 3120, Col. Arcos Vallarta, Guadalajara',
            ],
            [
                'nombre' => 'Beatriz Núñez Carrillo',
                'especialidad' => 'Geriatría',
                'telefono' => '8125589032',
                'telefono_format' => '81 2558 9032',
                'direccion' => 'Av. Revolución 2150, Monterrey, NL',
            ],
            [
                'nombre' => 'Carlos Hernández Pineda',
                'especialidad' => 'Cirugía General',
                'telefono' => '5578123345',
                'telefono_format' => '55 7812 3345',
                'direccion' => 'Calz. de Tlalpan 3100, Col. Ex Hacienda Coapa, CDMX',
            ],
            [
                'nombre' => 'Cecilia Torres Aguilar',
                'especialidad' => 'Endocrinología',
                'telefono' => '5560129981',
                'telefono_format' => '55 6012 9981',
                'direccion' => 'Av. Patriotismo 210, Col. Escandón, CDMX',
            ],
            [
                'nombre' => 'Daniel Ortega Ríos',
                'especialidad' => 'Medicina de Urgencias',
                'telefono' => '8130097712',
                'telefono_format' => '81 3009 7712',
                'direccion' => 'Av. Aztlán 410, Monterrey, NL',
            ],
            [
                'nombre' => 'Eduardo Cortés Silva',
                'especialidad' => 'Oftalmología',
                'telefono' => '8125549001',
                'telefono_format' => '81 2554 9001',
                'direccion' => 'Av. Constitución 1900, Monterrey, NL',
            ],
            [
                'nombre' => 'Fernanda Ruiz Gómez',
                'especialidad' => 'Ginecología y Obstetricia',
                'telefono' => '5530984421',
                'telefono_format' => '55 3098 4421',
                'direccion' => 'Calle Dakota 95, Col. Nápoles, CDMX',
            ],
            [
                'nombre' => 'Gabriela Méndez Rangel',
                'especialidad' => 'Pediatría',
                'telefono' => '3314428891',
                'telefono_format' => '33 1442 8891',
                'direccion' => 'Av. Américas 1254, Col. Country Club, Guadalajara',
            ],
            [
                'nombre' => 'Héctor Ramírez Luna',
                'especialidad' => 'Cardiología',
                'telefono' => '5566772134',
                'telefono_format' => '55 6677 2134',
                'direccion' => 'Av. Universidad 1200, Col. Xoco, CDMX',
            ],
            [
                'nombre' => 'Iván Morales Ruiz',
                'especialidad' => 'Anestesiología',
                'telefono' => '3311897745',
                'telefono_format' => '33 1189 7745',
                'direccion' => 'Av. Pablo Neruda 2400, Col. Providencia, Guadalajara',
            ],
            [
                'nombre' => 'Jorge Salinas Cruz',
                'especialidad' => 'Neumología',
                'telefono' => '5544217800',
                'telefono_format' => '55 4421 7800',
                'direccion' => 'Calz. de los Misterios 120, Gustavo A. Madero, CDMX',
            ],
            [
                'nombre' => 'Karla Aguilar Moreno',
                'especialidad' => 'Cirugía Plástica',
                'telefono' => '5541126654',
                'telefono_format' => '55 4112 6654',
                'direccion' => 'Av. Masaryk 111, Polanco, CDMX',
            ],
            [
                'nombre' => 'Luis Alberto Sánchez Torres',
                'especialidad' => 'Urología',
                'telefono' => '3325679912',
                'telefono_format' => '33 2567 9912',
                'direccion' => 'Av. México 3370, Col. Monraz, Guadalajara',
            ],
            [
                'nombre' => 'Mariana López Estrada',
                'especialidad' => 'Pediatría',
                'telefono' => '8114457789',
                'telefono_format' => '81 1445 7789',
                'direccion' => 'Av. Vasconcelos 420, San Pedro Garza García, NL',
            ],
            [
                'nombre' => 'Óscar Vázquez Beltrán',
                'especialidad' => 'Anestesiología',
                'telefono' => '5590083344',
                'telefono_format' => '55 9008 3344',
                'direccion' => 'Av. Observatorio 350, Miguel Hidalgo, CDMX',
            ],
            [
                'nombre' => 'Paola Jiménez Calderón',
                'especialidad' => 'Dermatología',
                'telefono' => '5590015588',
                'telefono_format' => '55 9001 5588',
                'direccion' => 'Río Lerma 160, Col. Cuauhtémoc, CDMX',
            ],
            [
                'nombre' => 'Ricardo Mendoza Salas',
                'especialidad' => 'Neurocirugía',
                'telefono' => '8132218844',
                'telefono_format' => '81 3221 8844',
                'direccion' => 'Av. Gonzalitos 500, Mitras Centro, Monterrey',
            ],
            [
                'nombre' => 'Sofía Ramírez Castillo',
                'especialidad' => 'Medicina Interna',
                'telefono' => '5573349921',
                'telefono_format' => '55 7334 9921',
                'direccion' => 'Eje Central Lázaro Cárdenas 980, CDMX',
            ],
            [
                'nombre' => 'Tomás Herrera Velasco',
                'especialidad' => 'Reumatología',
                'telefono' => '3341206678',
                'telefono_format' => '33 4120 6678',
                'direccion' => 'Av. Niño Obrero 800, Zapopan, Jal.',
            ],
            [
                'nombre' => 'Valeria Ponce Aguilar',
                'especialidad' => 'Nutriología Clínica',
                'telefono' => '5555609987',
                'telefono_format' => '55 5560 9987',
                'direccion' => 'Av. División del Norte 2400, Coyoacán, CDMX',
            ],
        ];

        $especialidades = [
            'Alergología',
            'Algología (Clínica del Dolor)',
            'Anestesiología',
            'Angiología y Cirugía Vascular',
            'Audiología, Otoneurología y Foniatría',
            'Cardiología',
            'Cardiología Pediátrica',
            'Cirugía Cardiotorácica',
            'Cirugía de Trasplantes',
            'Cirugía General',
            'Cirugía Maxilofacial',
            'Cirugía Oncológica',
            'Cirugía Pediátrica',
            'Cirugía Plástica, Estética y Reconstructiva',
            'Coloproctología',
            'Dermatología',
            'Endocrinología',
            'Gastroenterología',
            'Gastroenterología Pediátrica',
            'Geriatría',
            'Ginecología y Obstetricia',
            'Hematología',
            'Infectología',
            'Medicina del Deporte',
            'Medicina Familiar',
            'Medicina Física y Rehabilitación',
            'Medicina Interna',
            'Medicina Paliativa',
            'Nefrología',
            'Nefrología Pediátrica',
            'Neonatología',
            'Neumología',
            'Neurocirugía',
            'Neurología',
            'Neurología Pediátrica',
            'Nutriología Clínica',
            'Oftalmología',
            'Oncología Médica',
            'Oncología Pediátrica',
            'Ortopedia y Traumatología',
            'Otorrinolaringología',
            'Paidopsiquiatría',
            'Pediatría',
            'Psicología Clínica',
            'Psiquiatría',
            'Psiquiatría Infantil y del Adolescente',
            'Reumatología',
            'Salud Pública',
            'Urología',
        ];

        $doctoresPorEspecialidad = collect($doctores)->groupBy('especialidad');

        $estudios = [
            'Estudios de Cardiología' => [
                ['nombre' => 'Ecocardiograma', 'precio' => 5200],
                ['nombre' => 'Ecocardiograma Fetal', 'precio' => 5200],
                ['nombre' => 'Ecocardiograma Transesofágico', 'precio' => 6630],
                ['nombre' => 'Ecocardiograma de Estrés', 'precio' => 8450],
                ['nombre' => 'Monitoreo Holter 24 horas', 'precio' => 3250],
                ['nombre' => 'MAPA (Monitoreo Ambulatorio de Presión Arterial)', 'precio' => 3250],
                ['nombre' => 'Electrocardiograma', 'precio' => 520],
                ['nombre' => 'Valoración cardiológica básica', 'precio' => 2600],
                ['nombre' => 'Valoración cardiológica completa', 'precio' => 3380],
                ['nombre' => 'Consulta cardiológica', 'precio' => 1300],
                ['nombre' => 'Prueba de esfuerzo', 'precio' => 3250],
                ['nombre' => 'Placa de tórax', 'precio' => 1716],
            ],

            'Tomografías' => [
                ['nombre' => 'TAC de cráneo simple', 'precio' => 2640],
                ['nombre' => 'TAC de cráneo contrastada', 'precio' => 4498],
                ['nombre' => 'TAC de hipófisis contrastada', 'precio' => 4498],
                ['nombre' => 'TAC facial simple', 'precio' => 3120],
                ['nombre' => 'TAC de senos paranasales', 'precio' => 3120],
                ['nombre' => 'TAC de órbitas', 'precio' => 3120],
                ['nombre' => 'TAC de oído', 'precio' => 3120],
                ['nombre' => 'TAC de cuello simple', 'precio' => 3380],
                ['nombre' => 'TAC de cuello contrastada', 'precio' => 4758],
                ['nombre' => 'TAC de laringe simple', 'precio' => 3380],
                ['nombre' => 'TAC de laringe contrastada', 'precio' => 4758],
                ['nombre' => 'TAC de tórax simple', 'precio' => 5720],
                ['nombre' => 'TAC de tórax contrastada', 'precio' => 7098],
                ['nombre' => 'TAC de abdomen simple', 'precio' => 5720],
                ['nombre' => 'TAC de abdomen contrastada', 'precio' => 7098],
                ['nombre' => 'TAC de pelvis simple', 'precio' => 5720],
                ['nombre' => 'TAC de pelvis contrastada', 'precio' => 7098],
            ],
        ];

        $serviciosMedicos = [
            'Ortopedia y Traumatología' => [
                ['procedimiento' => 'Prótesis total de cadera (artroplastia)', 'cuota' => 10000],
                ['procedimiento' => 'Prótesis total de rodilla (artroplastia)', 'cuota' => 10000],
                ['procedimiento' => 'Artroscopia de rodilla – meniscos', 'cuota' => 10000],
                ['procedimiento' => 'Reconstrucción de ligamento cruzado anterior', 'cuota' => 10000],
                ['procedimiento' => 'Cirugía de síndrome del túnel carpiano', 'cuota' => 10000],
            ],

            'Urología' => [
                ['procedimiento' => 'Resección transuretral de próstata (RTUP)', 'cuota' => 10000],
                ['procedimiento' => 'Sistema Urolift', 'cuota' => 10000],
                ['procedimiento' => 'Circuncisión / Fimosis', 'cuota' => 10000],
                ['procedimiento' => 'Cirugía de próstata con vapor de agua (Rezum)', 'cuota' => 10000],
            ],

            'Cirugía General' => [
                ['procedimiento' => 'Apendicectomía', 'cuota' => 10000],
                ['procedimiento' => 'Colecistectomía laparoscópica', 'cuota' => 10000],
                ['procedimiento' => 'Hernioplastía inguinal', 'cuota' => 10000],
                ['procedimiento' => 'Cirugía de tiroides (tiroidectomía)', 'cuota' => 10000],
            ],

            'Ginecología y Obstetricia' => [
                ['procedimiento' => 'Cesárea', 'cuota' => 10000],
                ['procedimiento' => 'Histerectomía laparoscópica', 'cuota' => 10000],
                ['procedimiento' => 'Legrado uterino', 'cuota' => 10000],
                ['procedimiento' => 'Cirugía de prolapso uterino', 'cuota' => 10000],
            ],

            'Cirugía Plástica' => [
                ['procedimiento' => 'Abdominoplastia', 'cuota' => 10000],
                ['procedimiento' => 'Aumento mamario con implantes', 'cuota' => 10000],
                ['procedimiento' => 'Liposucción asistida (VASER / Lipo HD)', 'cuota' => 10000],
                ['procedimiento' => 'Rinoplastia (estética y/o funcional)', 'cuota' => 10000],
            ],
        ];

        $hospitalesMock = [
            [
                'nombre' => 'Fifty Doctors Angelópolis',
                'direccion' => 'Anillo Perif. Ecológico 3505, Tlaxcalancingo, San Andrés Cholula, Pue.',
                'telefono' => '2226892995',
                'horario' => 'Abierto las 24 hrs',
                'imagen' => 'images/hospitals/angelopolis.jpg',
            ],
            [
                'nombre' => 'Fifty Doctors San Manuel',
                'direccion' => 'Blvrd 14 Sur 4302, Jardines de San Manuel, Puebla',
                'telefono' => '2226895140',
                'horario' => 'Abierto las 24 hrs',
                'imagen' => 'images/hospitals/san-manuel.jpg',
            ],
            [
                'nombre' => 'Fifty Doctors Homi La Paz',
                'direccion' => 'Av. Teziutlán Sur 36, Col. La Paz, Puebla',
                'telefono' => '2226895140',
                'horario' => 'Abierto las 24 hrs',
                'imagen' => 'images/hospitals/la-paz.jpg',
            ],
        ];

        $medicamentos = [
            ['nombre' => '11-Desoxicorticosterona', 'precio' => 7042.04],
            ['nombre' => '17-Cetosteroides 17-KS en orina', 'precio' => 1133.63],
            ['nombre' => '17-Hidroxi corticoesteroides 17-OHCS', 'precio' => 1133.63],
            ['nombre' => '17-Alfa-Hidroxi-Progesterona (17-OHP)', 'precio' => 533.03],
            ['nombre' => 'Acetaminofén (Tylenol)', 'precio' => 1111.11],
            ['nombre' => 'Acetona en orina', 'precio' => 234.23],
            ['nombre' => 'Ácido fólico', 'precio' => 555.56],
            ['nombre' => 'Ácido úrico en suero', 'precio' => 87.09],
            ['nombre' => 'Alcohol (Etanol)', 'precio' => 366.37],
            ['nombre' => 'Aldosterona en sangre', 'precio' => 1681.68],
            ['nombre' => 'Amilasa en suero', 'precio' => 138.14],
            ['nombre' => 'Anfetamina / Metanfetamina', 'precio' => 240.24],
            ['nombre' => 'Anticuerpos anti Citomegalovirus IGG', 'precio' => 247.75],
            ['nombre' => 'Anticuerpos anti Citomegalovirus IGM', 'precio' => 247.75],
            ['nombre' => 'Anticuerpos anti Cardiolipinas IGG e IGM', 'precio' => 1022.52],
        ];
    @endphp
